apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-jobs-job-production
  namespace: argocd
  annotations:
    godsAppName: job
    godsApplicationType: Job
    godsCluster: us-east-1
    godsTeamName: jobs
    godsEnv: production
    godsEnvConfigurationVersion: 19cf47f46de4352925b9cba292e80af0e291f00d
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-job'
    targetRevision: main
    
    helm:
      values: |
        404 page not found
        image: gitopsdevsolutions/job
        tag: latest
        createdAt: 2022-01-15 23:42:00 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: jobs-production