apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-jobs-job-production
  namespace: argocd
  annotations:
    godsAppName: job
    godsApplicationType: Job
    godsCluster: us-east-1
    godsTeamName: jobs
    godsEnv: production
    godsEnvConfigurationVersion: c7f5f4a704d1f9c7a21ab728a2c600b4a01e4c95
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-job'
    targetRevision: main
    helm:
      values: |
        env:
          GODS_DURATION: "10"
          GODS_SHOULD_FAIL: false
        image: gitopsdevsolutions/job
        tag: latest
        createdAt: 2022-01-14 10:47:49 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: jobs-production