apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-microservices-microservice-production
  namespace: argocd
  annotations:
    godsAppName: microservice
    
    godsCluster: us-east-1
    godsTeamName: microservices
    godsEnv: production
    godsEnvConfigurationVersion: 01ea4a670c4cf9bd90f9e0d994321ae128c68c89
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-app'
    targetRevision: main
    helm:
      values: |
        env:
          GODS_DURATION: "10"
          GODS_SHOULD_FAIL: false
        image: gitopsdevsolutions/microservice
        tag: latest
        createdAt: 2022-01-15 23:43:41 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-production