apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-third-party-secret-production
  namespace: argocd
  annotations:
    godsAppName: secret
    godsApplicationType: Manifest
    godsCluster: us-east-1
    godsTeamName: third-party
    godsEnv: production
    godsEnvConfigurationVersion: db23c8530e7bca92c660a923877fa7da70d402a7
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions-carmel/gitops-cd'
    targetRevision: main
    path: ''
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: third-party-production